import { SetMetadata } from "@nestjs/common";

export enum RotinaReference {
	AUTH = "AUTH",
	PAINEL_ADM = "PAINEL_ADM",
	ACESSOS = "ACESSOS",
	RASTREIO_PRONTUARIOS = "RASTREIO_PRONTUARIOS",
	LINKS_RAPIDOS = "LINKS_RAPIDOS",
	ARQUIVOS = "ARQUIVOS",
	FACILIDADES = "FACILIDADES",
	CARDAPIOS = "CARDAPIOS",
	CENTRAL_AVISOS = "CENTRAL_AVISOS",
	SQL_IMPORTS = "SQL_IMPORTS",
	IMPRESSORAS = "IMPRESSORAS",
	MARCA = "MARCA",
	MODELO = "MODELO",
	DRT = "DRT",
	OUVIDORIA = "OUVIDORIA",
	CAD_ACESSO = "CAD-ACESSO",
	EXTRANET = "EXTRANET",
	RAMAIS = "RAMAIS",
	INTRANET = "INTRANET",
	BI = "BI",
	HOST_REDE = "HOST_REDE",
	SETORES = "SETORES",
	TIPO_CADASTRO = "TIPO_CADASTRO",
	INTERFACE_REDE = "INTERFACE_REDE",
	CHAT = "CHAT",
	TI = "TI",
}

export const REFERENCE_KEY = "reference";
export const Reference = (reference: RotinaReference) =>
	SetMetadata(REFERENCE_KEY, reference);
